#!/bin/bash

echo "Setting up GitHub repository for humanoid-robotics-book"
echo ""
echo "Please follow these steps:"
echo "1. Go to https://github.com and log in to your account"
echo "2. Click the '+' icon in the top right corner and select 'New repository'"
echo "3. Set the repository name to 'humanoid-robotics-book'"
echo "4. Set the repository to 'Public' (required for GitHub Pages)"
echo "5. Do NOT initialize with README, .gitignore, or license (we already have these)"
echo "6. Click 'Create repository'"
echo ""
echo "After creating the repository, copy the HTTPS clone URL (e.g., https://github.com/YOUR-USERNAME/humanoid-robotics-book.git)"
echo ""
echo "Then run the following commands (replace the URL with your actual repository URL):"
echo ""
echo "git remote add origin YOUR_REPOSITORY_URL"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "After pushing the code, to deploy to GitHub Pages, run:"
echo "cd docusaurus"
echo "npm run deploy"
echo ""
echo "This will build and deploy your Docusaurus site to GitHub Pages."